"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from flypix.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .annotationgeometrypayload import (
        AnnotationGeometryPayload,
        AnnotationGeometryPayloadTypedDict,
    )
    from .anymessagecontext import (
        AnyMessageContext,
        AnyMessageContextTypedDict,
        UnknownAnyMessageContext,
    )
    from .applymodelrequest import ApplyModelRequest, ApplyModelRequestTypedDict
    from .applymodelresponse import ApplyModelResponse, ApplyModelResponseTypedDict
    from .artifactresponse import ArtifactResponse, ArtifactResponseTypedDict
    from .artifacttype import ArtifactType
    from .balanceresponse import BalanceResponse, BalanceResponseTypedDict
    from .body_upload_geojson_vectors_vector_id_upload_geojson_post import (
        BodyUploadGeojsonVectorsVectorIDUploadGeojsonPost,
        BodyUploadGeojsonVectorsVectorIDUploadGeojsonPostTypedDict,
    )
    from .body_upload_geopkg import BodyUploadGeopkg, BodyUploadGeopkgTypedDict
    from .body_upload_shapefile import BodyUploadShapefile, BodyUploadShapefileTypedDict
    from .chatmessageresponse import ChatMessageResponse, ChatMessageResponseTypedDict
    from .classresponse import ClassResponse, ClassResponseTypedDict
    from .cogsource import COGSource, COGSourceTypedDict
    from .createannotationsrequest import (
        CreateAnnotationsRequest,
        CreateAnnotationsRequestTypedDict,
    )
    from .createartifactrequest import (
        CreateArtifactRequest,
        CreateArtifactRequestTypedDict,
    )
    from .createclassrequest import CreateClassRequest, CreateClassRequestTypedDict
    from .createmanyregionsrequest import (
        CreateManyRegionsRequest,
        CreateManyRegionsRequestTypedDict,
    )
    from .createregionpayload import CreateRegionPayload, CreateRegionPayloadTypedDict
    from .createvectorforvisiblefile import (
        CreateVectorForVisibleFile,
        CreateVectorForVisibleFileTypedDict,
    )
    from .datacontext import DataContext, DataContextTypedDict
    from .entitydeletionresponse import (
        EntityDeletionResponse,
        EntityDeletionResponseTypedDict,
    )
    from .estimatemodelresponse import (
        EstimateModelResponse,
        EstimateModelResponseTypedDict,
    )
    from .filelinkresponse import FileLinkResponse, FileLinkResponseTypedDict
    from .fileresponse import FileResponse, FileResponseTypedDict
    from .files_deleteop import FilesDeleteRequest, FilesDeleteRequestTypedDict
    from .files_get_download_linkop import (
        FilesGetDownloadLinkRequest,
        FilesGetDownloadLinkRequestTypedDict,
    )
    from .files_get_storage_usageop import (
        FilesGetStorageUsageRequest,
        FilesGetStorageUsageRequestTypedDict,
    )
    from .files_get_visible_rasterop import (
        FilesGetVisibleRasterRequest,
        FilesGetVisibleRasterRequestTypedDict,
    )
    from .files_getop import FilesGetRequest, FilesGetRequestTypedDict
    from .files_list_for_folderop import (
        FilesListForFolderRequest,
        FilesListForFolderRequestTypedDict,
    )
    from .files_list_for_projectop import (
        FilesListForProjectRequest,
        FilesListForProjectRequestTypedDict,
    )
    from .files_upload_from_urlop import (
        FilesUploadFromURLRequest,
        FilesUploadFromURLRequestTypedDict,
    )
    from .files_upload_v2op import FilesUploadV2Request, FilesUploadV2RequestTypedDict
    from .files_uploadop import FilesUploadRequest, FilesUploadRequestTypedDict
    from .filestatus import FileStatus
    from .filetype import FileType
    from .foldercreationrequest import (
        FolderCreationRequest,
        FolderCreationRequestTypedDict,
    )
    from .folderresponse import FolderResponse, FolderResponseTypedDict
    from .folders_deleteop import FoldersDeleteRequest, FoldersDeleteRequestTypedDict
    from .folders_list_for_folderop import (
        FoldersListForFolderRequest,
        FoldersListForFolderRequestTypedDict,
    )
    from .folders_list_for_projectop import (
        FoldersListForProjectRequest,
        FoldersListForProjectRequestTypedDict,
    )
    from .geosense_create_artifactop import (
        GeosenseCreateArtifactRequest,
        GeosenseCreateArtifactRequestTypedDict,
    )
    from .geosense_create_sessionop import (
        GeosenseCreateSessionRequest,
        GeosenseCreateSessionRequestTypedDict,
    )
    from .geosense_get_artifactop import (
        GeosenseGetArtifactRequest,
        GeosenseGetArtifactRequestTypedDict,
    )
    from .geosense_send_messageop import (
        GeosenseSendMessageRequest,
        GeosenseSendMessageRequestTypedDict,
    )
    from .inferenceresponse import InferenceResponse, InferenceResponseTypedDict
    from .inferences_list_for_fileop import (
        InferencesListForFileRequest,
        InferencesListForFileRequestTypedDict,
    )
    from .inferences_list_for_projectop import (
        InferencesListForProjectRequest,
        InferencesListForProjectRequestTypedDict,
    )
    from .inferences_list_for_tenantop import (
        InferencesListForTenantRequest,
        InferencesListForTenantRequestTypedDict,
    )
    from .inferencestatus import InferenceStatus
    from .loginrequest import LoginRequest, LoginRequestTypedDict
    from .loginresponse import LoginResponse, LoginResponseTypedDict
    from .models_applyop import ModelsApplyRequest, ModelsApplyRequestTypedDict
    from .models_deleteop import ModelsDeleteRequest, ModelsDeleteRequestTypedDict
    from .models_estimate_applicationop import (
        ModelsEstimateApplicationRequest,
        ModelsEstimateApplicationRequestTypedDict,
    )
    from .models_get_inference_statusop import (
        ModelsGetInferenceStatusRequest,
        ModelsGetInferenceStatusRequestTypedDict,
    )
    from .models_list_for_projectop import (
        ModelsListForProjectRequest,
        ModelsListForProjectRequestTypedDict,
    )
    from .models_list_for_tenantop import (
        ModelsListForTenantRequest,
        ModelsListForTenantRequestTypedDict,
    )
    from .modelstatus import ModelStatus
    from .officialmodelresponse import (
        OfficialModelResponse,
        OfficialModelResponseTypedDict,
    )
    from .payments_get_balanceop import (
        PaymentsGetBalanceRequest,
        PaymentsGetBalanceRequestTypedDict,
    )
    from .privatemodelresponse import (
        PrivateModelResponse,
        PrivateModelResponseTypedDict,
    )
    from .projectcreationrequest import (
        ProjectCreationRequest,
        ProjectCreationRequestTypedDict,
    )
    from .projectresponse import ProjectResponse, ProjectResponseTypedDict
    from .projects_deleteop import ProjectsDeleteRequest, ProjectsDeleteRequestTypedDict
    from .projects_list_for_tenantop import (
        ProjectsListForTenantRequest,
        ProjectsListForTenantRequestTypedDict,
    )
    from .rasterresponse import RasterResponse, RasterResponseTypedDict
    from .rasters_list_for_fileop import (
        RastersListForFileRequest,
        RastersListForFileRequestTypedDict,
    )
    from .rasters_list_for_projectop import (
        RastersListForProjectRequest,
        RastersListForProjectRequestTypedDict,
    )
    from .rasters_list_for_tenantop import (
        RastersListForTenantRequest,
        RastersListForTenantRequestTypedDict,
    )
    from .rastersource import RasterSource, RasterSourceTypedDict
    from .rasterstatus import RasterStatus
    from .reason import Reason
    from .refreshrequest import RefreshRequest, RefreshRequestTypedDict
    from .regioninferencebehavior import RegionInferenceBehavior
    from .regionmetadata import RegionMetadata, RegionMetadataTypedDict
    from .regionresponse import RegionResponse, RegionResponseTypedDict
    from .regions_createop import RegionsCreateRequest, RegionsCreateRequestTypedDict
    from .regions_list_for_fileop import (
        RegionsListForFileRequest,
        RegionsListForFileRequestTypedDict,
    )
    from .regiontrainingbehavior import RegionTrainingBehavior
    from .responsestatus import ResponseStatus
    from .security import Security, SecurityTypedDict
    from .sendmessagerequest import SendMessageRequest, SendMessageRequestTypedDict
    from .tenantresponse import TenantResponse, TenantResponseTypedDict
    from .transaction import Transaction, TransactionTypedDict
    from .transactiontype import TransactionType
    from .uploadannotationsresponse import (
        Errored,
        ErroredTypedDict,
        UploadAnnotationsResponse,
        UploadAnnotationsResponseTypedDict,
    )
    from .uploadfileresponsestatus import (
        UploadFileResponseStatus,
        UploadFileResponseStatusTypedDict,
    )
    from .uploadsource import UploadSource, UploadSourceTypedDict
    from .usageresponse import UsageResponse, UsageResponseTypedDict
    from .vectorcreationsource import VectorCreationSource
    from .vectorfeatures import VectorFeatures, VectorFeaturesTypedDict
    from .vectorfeaturesdict import VectorFeaturesDict, VectorFeaturesDictTypedDict
    from .vectormetadata import VectorMetadata, VectorMetadataTypedDict
    from .vectorresponse import VectorResponse, VectorResponseTypedDict
    from .vectors_create_annotationsop import (
        VectorsCreateAnnotationsRequest,
        VectorsCreateAnnotationsRequestTypedDict,
    )
    from .vectors_create_classop import (
        VectorsCreateClassRequest,
        VectorsCreateClassRequestTypedDict,
    )
    from .vectors_deleteop import VectorsDeleteRequest, VectorsDeleteRequestTypedDict
    from .vectors_get_featuresop import (
        VectorsGetFeaturesRequest,
        VectorsGetFeaturesRequestTypedDict,
    )
    from .vectors_list_classes_for_projectop import (
        VectorsListClassesForProjectRequest,
        VectorsListClassesForProjectRequestTypedDict,
    )
    from .vectors_list_for_fileop import (
        VectorsListForFileRequest,
        VectorsListForFileRequestTypedDict,
    )
    from .vectors_upload_geojsonop import (
        VectorsUploadGeojsonRequest,
        VectorsUploadGeojsonRequestTypedDict,
    )
    from .vectors_upload_gpkgop import (
        VectorsUploadGpkgRequest,
        VectorsUploadGpkgRequestTypedDict,
    )
    from .vectors_upload_shapefileop import (
        VectorsUploadShapefileRequest,
        VectorsUploadShapefileRequestTypedDict,
    )
    from .wmtssource import WMTSSource, WMTSSourceTypedDict

__all__ = [
    "AnnotationGeometryPayload",
    "AnnotationGeometryPayloadTypedDict",
    "AnyMessageContext",
    "AnyMessageContextTypedDict",
    "ApplyModelRequest",
    "ApplyModelRequestTypedDict",
    "ApplyModelResponse",
    "ApplyModelResponseTypedDict",
    "ArtifactResponse",
    "ArtifactResponseTypedDict",
    "ArtifactType",
    "BalanceResponse",
    "BalanceResponseTypedDict",
    "BodyUploadGeojsonVectorsVectorIDUploadGeojsonPost",
    "BodyUploadGeojsonVectorsVectorIDUploadGeojsonPostTypedDict",
    "BodyUploadGeopkg",
    "BodyUploadGeopkgTypedDict",
    "BodyUploadShapefile",
    "BodyUploadShapefileTypedDict",
    "COGSource",
    "COGSourceTypedDict",
    "ChatMessageResponse",
    "ChatMessageResponseTypedDict",
    "ClassResponse",
    "ClassResponseTypedDict",
    "CreateAnnotationsRequest",
    "CreateAnnotationsRequestTypedDict",
    "CreateArtifactRequest",
    "CreateArtifactRequestTypedDict",
    "CreateClassRequest",
    "CreateClassRequestTypedDict",
    "CreateManyRegionsRequest",
    "CreateManyRegionsRequestTypedDict",
    "CreateRegionPayload",
    "CreateRegionPayloadTypedDict",
    "CreateVectorForVisibleFile",
    "CreateVectorForVisibleFileTypedDict",
    "DataContext",
    "DataContextTypedDict",
    "EntityDeletionResponse",
    "EntityDeletionResponseTypedDict",
    "Errored",
    "ErroredTypedDict",
    "EstimateModelResponse",
    "EstimateModelResponseTypedDict",
    "FileLinkResponse",
    "FileLinkResponseTypedDict",
    "FileResponse",
    "FileResponseTypedDict",
    "FileStatus",
    "FileType",
    "FilesDeleteRequest",
    "FilesDeleteRequestTypedDict",
    "FilesGetDownloadLinkRequest",
    "FilesGetDownloadLinkRequestTypedDict",
    "FilesGetRequest",
    "FilesGetRequestTypedDict",
    "FilesGetStorageUsageRequest",
    "FilesGetStorageUsageRequestTypedDict",
    "FilesGetVisibleRasterRequest",
    "FilesGetVisibleRasterRequestTypedDict",
    "FilesListForFolderRequest",
    "FilesListForFolderRequestTypedDict",
    "FilesListForProjectRequest",
    "FilesListForProjectRequestTypedDict",
    "FilesUploadFromURLRequest",
    "FilesUploadFromURLRequestTypedDict",
    "FilesUploadRequest",
    "FilesUploadRequestTypedDict",
    "FilesUploadV2Request",
    "FilesUploadV2RequestTypedDict",
    "FolderCreationRequest",
    "FolderCreationRequestTypedDict",
    "FolderResponse",
    "FolderResponseTypedDict",
    "FoldersDeleteRequest",
    "FoldersDeleteRequestTypedDict",
    "FoldersListForFolderRequest",
    "FoldersListForFolderRequestTypedDict",
    "FoldersListForProjectRequest",
    "FoldersListForProjectRequestTypedDict",
    "GeosenseCreateArtifactRequest",
    "GeosenseCreateArtifactRequestTypedDict",
    "GeosenseCreateSessionRequest",
    "GeosenseCreateSessionRequestTypedDict",
    "GeosenseGetArtifactRequest",
    "GeosenseGetArtifactRequestTypedDict",
    "GeosenseSendMessageRequest",
    "GeosenseSendMessageRequestTypedDict",
    "InferenceResponse",
    "InferenceResponseTypedDict",
    "InferenceStatus",
    "InferencesListForFileRequest",
    "InferencesListForFileRequestTypedDict",
    "InferencesListForProjectRequest",
    "InferencesListForProjectRequestTypedDict",
    "InferencesListForTenantRequest",
    "InferencesListForTenantRequestTypedDict",
    "LoginRequest",
    "LoginRequestTypedDict",
    "LoginResponse",
    "LoginResponseTypedDict",
    "ModelStatus",
    "ModelsApplyRequest",
    "ModelsApplyRequestTypedDict",
    "ModelsDeleteRequest",
    "ModelsDeleteRequestTypedDict",
    "ModelsEstimateApplicationRequest",
    "ModelsEstimateApplicationRequestTypedDict",
    "ModelsGetInferenceStatusRequest",
    "ModelsGetInferenceStatusRequestTypedDict",
    "ModelsListForProjectRequest",
    "ModelsListForProjectRequestTypedDict",
    "ModelsListForTenantRequest",
    "ModelsListForTenantRequestTypedDict",
    "OfficialModelResponse",
    "OfficialModelResponseTypedDict",
    "PaymentsGetBalanceRequest",
    "PaymentsGetBalanceRequestTypedDict",
    "PrivateModelResponse",
    "PrivateModelResponseTypedDict",
    "ProjectCreationRequest",
    "ProjectCreationRequestTypedDict",
    "ProjectResponse",
    "ProjectResponseTypedDict",
    "ProjectsDeleteRequest",
    "ProjectsDeleteRequestTypedDict",
    "ProjectsListForTenantRequest",
    "ProjectsListForTenantRequestTypedDict",
    "RasterResponse",
    "RasterResponseTypedDict",
    "RasterSource",
    "RasterSourceTypedDict",
    "RasterStatus",
    "RastersListForFileRequest",
    "RastersListForFileRequestTypedDict",
    "RastersListForProjectRequest",
    "RastersListForProjectRequestTypedDict",
    "RastersListForTenantRequest",
    "RastersListForTenantRequestTypedDict",
    "Reason",
    "RefreshRequest",
    "RefreshRequestTypedDict",
    "RegionInferenceBehavior",
    "RegionMetadata",
    "RegionMetadataTypedDict",
    "RegionResponse",
    "RegionResponseTypedDict",
    "RegionTrainingBehavior",
    "RegionsCreateRequest",
    "RegionsCreateRequestTypedDict",
    "RegionsListForFileRequest",
    "RegionsListForFileRequestTypedDict",
    "ResponseStatus",
    "Security",
    "SecurityTypedDict",
    "SendMessageRequest",
    "SendMessageRequestTypedDict",
    "TenantResponse",
    "TenantResponseTypedDict",
    "Transaction",
    "TransactionType",
    "TransactionTypedDict",
    "UnknownAnyMessageContext",
    "UploadAnnotationsResponse",
    "UploadAnnotationsResponseTypedDict",
    "UploadFileResponseStatus",
    "UploadFileResponseStatusTypedDict",
    "UploadSource",
    "UploadSourceTypedDict",
    "UsageResponse",
    "UsageResponseTypedDict",
    "VectorCreationSource",
    "VectorFeatures",
    "VectorFeaturesDict",
    "VectorFeaturesDictTypedDict",
    "VectorFeaturesTypedDict",
    "VectorMetadata",
    "VectorMetadataTypedDict",
    "VectorResponse",
    "VectorResponseTypedDict",
    "VectorsCreateAnnotationsRequest",
    "VectorsCreateAnnotationsRequestTypedDict",
    "VectorsCreateClassRequest",
    "VectorsCreateClassRequestTypedDict",
    "VectorsDeleteRequest",
    "VectorsDeleteRequestTypedDict",
    "VectorsGetFeaturesRequest",
    "VectorsGetFeaturesRequestTypedDict",
    "VectorsListClassesForProjectRequest",
    "VectorsListClassesForProjectRequestTypedDict",
    "VectorsListForFileRequest",
    "VectorsListForFileRequestTypedDict",
    "VectorsUploadGeojsonRequest",
    "VectorsUploadGeojsonRequestTypedDict",
    "VectorsUploadGpkgRequest",
    "VectorsUploadGpkgRequestTypedDict",
    "VectorsUploadShapefileRequest",
    "VectorsUploadShapefileRequestTypedDict",
    "WMTSSource",
    "WMTSSourceTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AnnotationGeometryPayload": ".annotationgeometrypayload",
    "AnnotationGeometryPayloadTypedDict": ".annotationgeometrypayload",
    "AnyMessageContext": ".anymessagecontext",
    "AnyMessageContextTypedDict": ".anymessagecontext",
    "UnknownAnyMessageContext": ".anymessagecontext",
    "ApplyModelRequest": ".applymodelrequest",
    "ApplyModelRequestTypedDict": ".applymodelrequest",
    "ApplyModelResponse": ".applymodelresponse",
    "ApplyModelResponseTypedDict": ".applymodelresponse",
    "ArtifactResponse": ".artifactresponse",
    "ArtifactResponseTypedDict": ".artifactresponse",
    "ArtifactType": ".artifacttype",
    "BalanceResponse": ".balanceresponse",
    "BalanceResponseTypedDict": ".balanceresponse",
    "BodyUploadGeojsonVectorsVectorIDUploadGeojsonPost": ".body_upload_geojson_vectors_vector_id_upload_geojson_post",
    "BodyUploadGeojsonVectorsVectorIDUploadGeojsonPostTypedDict": ".body_upload_geojson_vectors_vector_id_upload_geojson_post",
    "BodyUploadGeopkg": ".body_upload_geopkg",
    "BodyUploadGeopkgTypedDict": ".body_upload_geopkg",
    "BodyUploadShapefile": ".body_upload_shapefile",
    "BodyUploadShapefileTypedDict": ".body_upload_shapefile",
    "ChatMessageResponse": ".chatmessageresponse",
    "ChatMessageResponseTypedDict": ".chatmessageresponse",
    "ClassResponse": ".classresponse",
    "ClassResponseTypedDict": ".classresponse",
    "COGSource": ".cogsource",
    "COGSourceTypedDict": ".cogsource",
    "CreateAnnotationsRequest": ".createannotationsrequest",
    "CreateAnnotationsRequestTypedDict": ".createannotationsrequest",
    "CreateArtifactRequest": ".createartifactrequest",
    "CreateArtifactRequestTypedDict": ".createartifactrequest",
    "CreateClassRequest": ".createclassrequest",
    "CreateClassRequestTypedDict": ".createclassrequest",
    "CreateManyRegionsRequest": ".createmanyregionsrequest",
    "CreateManyRegionsRequestTypedDict": ".createmanyregionsrequest",
    "CreateRegionPayload": ".createregionpayload",
    "CreateRegionPayloadTypedDict": ".createregionpayload",
    "CreateVectorForVisibleFile": ".createvectorforvisiblefile",
    "CreateVectorForVisibleFileTypedDict": ".createvectorforvisiblefile",
    "DataContext": ".datacontext",
    "DataContextTypedDict": ".datacontext",
    "EntityDeletionResponse": ".entitydeletionresponse",
    "EntityDeletionResponseTypedDict": ".entitydeletionresponse",
    "EstimateModelResponse": ".estimatemodelresponse",
    "EstimateModelResponseTypedDict": ".estimatemodelresponse",
    "FileLinkResponse": ".filelinkresponse",
    "FileLinkResponseTypedDict": ".filelinkresponse",
    "FileResponse": ".fileresponse",
    "FileResponseTypedDict": ".fileresponse",
    "FilesDeleteRequest": ".files_deleteop",
    "FilesDeleteRequestTypedDict": ".files_deleteop",
    "FilesGetDownloadLinkRequest": ".files_get_download_linkop",
    "FilesGetDownloadLinkRequestTypedDict": ".files_get_download_linkop",
    "FilesGetStorageUsageRequest": ".files_get_storage_usageop",
    "FilesGetStorageUsageRequestTypedDict": ".files_get_storage_usageop",
    "FilesGetVisibleRasterRequest": ".files_get_visible_rasterop",
    "FilesGetVisibleRasterRequestTypedDict": ".files_get_visible_rasterop",
    "FilesGetRequest": ".files_getop",
    "FilesGetRequestTypedDict": ".files_getop",
    "FilesListForFolderRequest": ".files_list_for_folderop",
    "FilesListForFolderRequestTypedDict": ".files_list_for_folderop",
    "FilesListForProjectRequest": ".files_list_for_projectop",
    "FilesListForProjectRequestTypedDict": ".files_list_for_projectop",
    "FilesUploadFromURLRequest": ".files_upload_from_urlop",
    "FilesUploadFromURLRequestTypedDict": ".files_upload_from_urlop",
    "FilesUploadV2Request": ".files_upload_v2op",
    "FilesUploadV2RequestTypedDict": ".files_upload_v2op",
    "FilesUploadRequest": ".files_uploadop",
    "FilesUploadRequestTypedDict": ".files_uploadop",
    "FileStatus": ".filestatus",
    "FileType": ".filetype",
    "FolderCreationRequest": ".foldercreationrequest",
    "FolderCreationRequestTypedDict": ".foldercreationrequest",
    "FolderResponse": ".folderresponse",
    "FolderResponseTypedDict": ".folderresponse",
    "FoldersDeleteRequest": ".folders_deleteop",
    "FoldersDeleteRequestTypedDict": ".folders_deleteop",
    "FoldersListForFolderRequest": ".folders_list_for_folderop",
    "FoldersListForFolderRequestTypedDict": ".folders_list_for_folderop",
    "FoldersListForProjectRequest": ".folders_list_for_projectop",
    "FoldersListForProjectRequestTypedDict": ".folders_list_for_projectop",
    "GeosenseCreateArtifactRequest": ".geosense_create_artifactop",
    "GeosenseCreateArtifactRequestTypedDict": ".geosense_create_artifactop",
    "GeosenseCreateSessionRequest": ".geosense_create_sessionop",
    "GeosenseCreateSessionRequestTypedDict": ".geosense_create_sessionop",
    "GeosenseGetArtifactRequest": ".geosense_get_artifactop",
    "GeosenseGetArtifactRequestTypedDict": ".geosense_get_artifactop",
    "GeosenseSendMessageRequest": ".geosense_send_messageop",
    "GeosenseSendMessageRequestTypedDict": ".geosense_send_messageop",
    "InferenceResponse": ".inferenceresponse",
    "InferenceResponseTypedDict": ".inferenceresponse",
    "InferencesListForFileRequest": ".inferences_list_for_fileop",
    "InferencesListForFileRequestTypedDict": ".inferences_list_for_fileop",
    "InferencesListForProjectRequest": ".inferences_list_for_projectop",
    "InferencesListForProjectRequestTypedDict": ".inferences_list_for_projectop",
    "InferencesListForTenantRequest": ".inferences_list_for_tenantop",
    "InferencesListForTenantRequestTypedDict": ".inferences_list_for_tenantop",
    "InferenceStatus": ".inferencestatus",
    "LoginRequest": ".loginrequest",
    "LoginRequestTypedDict": ".loginrequest",
    "LoginResponse": ".loginresponse",
    "LoginResponseTypedDict": ".loginresponse",
    "ModelsApplyRequest": ".models_applyop",
    "ModelsApplyRequestTypedDict": ".models_applyop",
    "ModelsDeleteRequest": ".models_deleteop",
    "ModelsDeleteRequestTypedDict": ".models_deleteop",
    "ModelsEstimateApplicationRequest": ".models_estimate_applicationop",
    "ModelsEstimateApplicationRequestTypedDict": ".models_estimate_applicationop",
    "ModelsGetInferenceStatusRequest": ".models_get_inference_statusop",
    "ModelsGetInferenceStatusRequestTypedDict": ".models_get_inference_statusop",
    "ModelsListForProjectRequest": ".models_list_for_projectop",
    "ModelsListForProjectRequestTypedDict": ".models_list_for_projectop",
    "ModelsListForTenantRequest": ".models_list_for_tenantop",
    "ModelsListForTenantRequestTypedDict": ".models_list_for_tenantop",
    "ModelStatus": ".modelstatus",
    "OfficialModelResponse": ".officialmodelresponse",
    "OfficialModelResponseTypedDict": ".officialmodelresponse",
    "PaymentsGetBalanceRequest": ".payments_get_balanceop",
    "PaymentsGetBalanceRequestTypedDict": ".payments_get_balanceop",
    "PrivateModelResponse": ".privatemodelresponse",
    "PrivateModelResponseTypedDict": ".privatemodelresponse",
    "ProjectCreationRequest": ".projectcreationrequest",
    "ProjectCreationRequestTypedDict": ".projectcreationrequest",
    "ProjectResponse": ".projectresponse",
    "ProjectResponseTypedDict": ".projectresponse",
    "ProjectsDeleteRequest": ".projects_deleteop",
    "ProjectsDeleteRequestTypedDict": ".projects_deleteop",
    "ProjectsListForTenantRequest": ".projects_list_for_tenantop",
    "ProjectsListForTenantRequestTypedDict": ".projects_list_for_tenantop",
    "RasterResponse": ".rasterresponse",
    "RasterResponseTypedDict": ".rasterresponse",
    "RastersListForFileRequest": ".rasters_list_for_fileop",
    "RastersListForFileRequestTypedDict": ".rasters_list_for_fileop",
    "RastersListForProjectRequest": ".rasters_list_for_projectop",
    "RastersListForProjectRequestTypedDict": ".rasters_list_for_projectop",
    "RastersListForTenantRequest": ".rasters_list_for_tenantop",
    "RastersListForTenantRequestTypedDict": ".rasters_list_for_tenantop",
    "RasterSource": ".rastersource",
    "RasterSourceTypedDict": ".rastersource",
    "RasterStatus": ".rasterstatus",
    "Reason": ".reason",
    "RefreshRequest": ".refreshrequest",
    "RefreshRequestTypedDict": ".refreshrequest",
    "RegionInferenceBehavior": ".regioninferencebehavior",
    "RegionMetadata": ".regionmetadata",
    "RegionMetadataTypedDict": ".regionmetadata",
    "RegionResponse": ".regionresponse",
    "RegionResponseTypedDict": ".regionresponse",
    "RegionsCreateRequest": ".regions_createop",
    "RegionsCreateRequestTypedDict": ".regions_createop",
    "RegionsListForFileRequest": ".regions_list_for_fileop",
    "RegionsListForFileRequestTypedDict": ".regions_list_for_fileop",
    "RegionTrainingBehavior": ".regiontrainingbehavior",
    "ResponseStatus": ".responsestatus",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "SendMessageRequest": ".sendmessagerequest",
    "SendMessageRequestTypedDict": ".sendmessagerequest",
    "TenantResponse": ".tenantresponse",
    "TenantResponseTypedDict": ".tenantresponse",
    "Transaction": ".transaction",
    "TransactionTypedDict": ".transaction",
    "TransactionType": ".transactiontype",
    "Errored": ".uploadannotationsresponse",
    "ErroredTypedDict": ".uploadannotationsresponse",
    "UploadAnnotationsResponse": ".uploadannotationsresponse",
    "UploadAnnotationsResponseTypedDict": ".uploadannotationsresponse",
    "UploadFileResponseStatus": ".uploadfileresponsestatus",
    "UploadFileResponseStatusTypedDict": ".uploadfileresponsestatus",
    "UploadSource": ".uploadsource",
    "UploadSourceTypedDict": ".uploadsource",
    "UsageResponse": ".usageresponse",
    "UsageResponseTypedDict": ".usageresponse",
    "VectorCreationSource": ".vectorcreationsource",
    "VectorFeatures": ".vectorfeatures",
    "VectorFeaturesTypedDict": ".vectorfeatures",
    "VectorFeaturesDict": ".vectorfeaturesdict",
    "VectorFeaturesDictTypedDict": ".vectorfeaturesdict",
    "VectorMetadata": ".vectormetadata",
    "VectorMetadataTypedDict": ".vectormetadata",
    "VectorResponse": ".vectorresponse",
    "VectorResponseTypedDict": ".vectorresponse",
    "VectorsCreateAnnotationsRequest": ".vectors_create_annotationsop",
    "VectorsCreateAnnotationsRequestTypedDict": ".vectors_create_annotationsop",
    "VectorsCreateClassRequest": ".vectors_create_classop",
    "VectorsCreateClassRequestTypedDict": ".vectors_create_classop",
    "VectorsDeleteRequest": ".vectors_deleteop",
    "VectorsDeleteRequestTypedDict": ".vectors_deleteop",
    "VectorsGetFeaturesRequest": ".vectors_get_featuresop",
    "VectorsGetFeaturesRequestTypedDict": ".vectors_get_featuresop",
    "VectorsListClassesForProjectRequest": ".vectors_list_classes_for_projectop",
    "VectorsListClassesForProjectRequestTypedDict": ".vectors_list_classes_for_projectop",
    "VectorsListForFileRequest": ".vectors_list_for_fileop",
    "VectorsListForFileRequestTypedDict": ".vectors_list_for_fileop",
    "VectorsUploadGeojsonRequest": ".vectors_upload_geojsonop",
    "VectorsUploadGeojsonRequestTypedDict": ".vectors_upload_geojsonop",
    "VectorsUploadGpkgRequest": ".vectors_upload_gpkgop",
    "VectorsUploadGpkgRequestTypedDict": ".vectors_upload_gpkgop",
    "VectorsUploadShapefileRequest": ".vectors_upload_shapefileop",
    "VectorsUploadShapefileRequestTypedDict": ".vectors_upload_shapefileop",
    "WMTSSource": ".wmtssource",
    "WMTSSourceTypedDict": ".wmtssource",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
