"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel
from typing_extensions import TypedDict


class AnnotationPayloadInputTypedDict(TypedDict):
    confidence: float
    polygon: str


class AnnotationPayloadInput(BaseModel):
    confidence: float

    polygon: str
