"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .datacontext import DataContext, DataContextTypedDict


AnyMessageContextInputTypedDict = DataContextTypedDict


AnyMessageContextInput = DataContext
