"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel
from typing_extensions import TypedDict


class ApplyModelRequestTypedDict(TypedDict):
    file_id: str
    r"""A string in UUID format"""


class ApplyModelRequest(BaseModel):
    file_id: str
    r"""A string in UUID format"""
