"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ApplyModelResponseTypedDict(TypedDict):
    inference_id: str
    status: str
    dollar_schema: NotRequired[str]
    r"""A URL to the JSON Schema for this object."""
    data: NotRequired[Dict[str, Any]]


class ApplyModelResponse(BaseModel):
    inference_id: str

    status: str

    dollar_schema: Annotated[Optional[str], pydantic.Field(alias="$schema")] = None
    r"""A URL to the JSON Schema for this object."""

    data: Optional[Dict[str, Any]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["$schema", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ApplyModelResponse.model_rebuild()
except NameError:
    pass
