"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel
from typing_extensions import TypedDict


class ApplyChangeDetectionInputBodyTypedDict(TypedDict):
    raster_id_a: str
    raster_id_b: str


class ApplyChangeDetectionInputBody(BaseModel):
    raster_id_a: str

    raster_id_b: str
