"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .artifacttype import ArtifactType
from datetime import datetime
from flypix.types import BaseModel
from typing import Any, Dict
from typing_extensions import TypedDict
from uuid import UUID


class ArtifactResponseTypedDict(TypedDict):
    artifact_id: UUID
    r"""A string in UUID format"""
    session_id: UUID
    r"""A string in UUID format"""
    tenant_id: UUID
    r"""A string in UUID format"""
    project_id: UUID
    r"""A string in UUID format"""
    created_at: datetime
    type: ArtifactType
    artifact_data: Dict[str, Any]


class ArtifactResponse(BaseModel):
    artifact_id: UUID
    r"""A string in UUID format"""

    session_id: UUID
    r"""A string in UUID format"""

    tenant_id: UUID
    r"""A string in UUID format"""

    project_id: UUID
    r"""A string in UUID format"""

    created_at: datetime

    type: ArtifactType

    artifact_data: Dict[str, Any]
