"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel
from flypix.utils import FieldMetadata
from typing_extensions import Annotated, TypedDict


class BodyUploadGeojsonVectorsVectorIDUploadGeojsonPostTypedDict(TypedDict):
    file: str


class BodyUploadGeojsonVectorsVectorIDUploadGeojsonPost(BaseModel):
    file: Annotated[str, FieldMetadata(multipart=True)]
