"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errormodel import ErrorModel, ErrorModelTypedDict
from .vectorresponse import VectorResponse, VectorResponseTypedDict
from typing import Union
from typing_extensions import TypeAliasType


CreateEmptyVectorResponseTypedDict = TypeAliasType(
    "CreateEmptyVectorResponseTypedDict",
    Union[VectorResponseTypedDict, ErrorModelTypedDict],
)


CreateEmptyVectorResponse = TypeAliasType(
    "CreateEmptyVectorResponse", Union[VectorResponse, ErrorModel]
)
