"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createregionpayload import CreateRegionPayload, CreateRegionPayloadTypedDict
from flypix.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class CreateManyRegionsRequestTypedDict(TypedDict):
    region_payloads: List[CreateRegionPayloadTypedDict]


class CreateManyRegionsRequest(BaseModel):
    region_payloads: List[CreateRegionPayload]
