"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errormodel import ErrorModel, ErrorModelTypedDict
from .projectresponse import ProjectResponse, ProjectResponseTypedDict
from typing import Union
from typing_extensions import TypeAliasType


CreateProjectResponseTypedDict = TypeAliasType(
    "CreateProjectResponseTypedDict",
    Union[ProjectResponseTypedDict, ErrorModelTypedDict],
)


CreateProjectResponse = TypeAliasType(
    "CreateProjectResponse", Union[ProjectResponse, ErrorModel]
)
