"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errormodel import ErrorModel, ErrorModelTypedDict
from .folderresponse import FolderResponse, FolderResponseTypedDict
from typing import Union
from typing_extensions import TypeAliasType


CreateFolderResponseTypedDict = TypeAliasType(
    "CreateFolderResponseTypedDict", Union[FolderResponseTypedDict, ErrorModelTypedDict]
)


CreateFolderResponse = TypeAliasType(
    "CreateFolderResponse", Union[FolderResponse, ErrorModel]
)
