"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel
from typing import Any, Dict, Literal
from typing_extensions import TypedDict


CreateSessionArtifactInputBodyType = Literal["data",]


class CreateSessionArtifactInputBodyTypedDict(TypedDict):
    artifact_data: Dict[str, Any]
    type: CreateSessionArtifactInputBodyType


class CreateSessionArtifactInputBody(BaseModel):
    artifact_data: Dict[str, Any]

    type: CreateSessionArtifactInputBodyType
