"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .annotationpayloadinput import (
    AnnotationPayloadInput,
    AnnotationPayloadInputTypedDict,
)
from flypix.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class CreateAnnotationsInVectorInputBodyTypedDict(TypedDict):
    class_id: str
    payload: Nullable[List[AnnotationPayloadInputTypedDict]]


class CreateAnnotationsInVectorInputBody(BaseModel):
    class_id: str

    payload: Nullable[List[AnnotationPayloadInput]]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
