"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel
from flypix.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class DataContextTypedDict(TypedDict):
    artifact_id: str
    r"""A string in UUID format"""
    type: Literal["data"]


class DataContext(BaseModel):
    artifact_id: str
    r"""A string in UUID format"""

    type: Annotated[
        Annotated[Literal["data"], AfterValidator(validate_const("data"))],
        pydantic.Field(alias="type"),
    ] = "data"


try:
    DataContext.model_rebuild()
except NameError:
    pass
