"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .entitydeletionresponse import (
    EntityDeletionResponse,
    EntityDeletionResponseTypedDict,
)
from .errormodel import ErrorModel, ErrorModelTypedDict
from flypix.types import BaseModel
from flypix.utils import FieldMetadata, PathParamMetadata
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class DeleteRasterRequestTypedDict(TypedDict):
    raster_id: str


class DeleteRasterRequest(BaseModel):
    raster_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


DeleteRasterResponseTypedDict = TypeAliasType(
    "DeleteRasterResponseTypedDict",
    Union[EntityDeletionResponseTypedDict, ErrorModelTypedDict],
)


DeleteRasterResponse = TypeAliasType(
    "DeleteRasterResponse", Union[EntityDeletionResponse, ErrorModel]
)
