"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Optional
from typing_extensions import NotRequired, TypedDict


class ErrorDetailTypedDict(TypedDict):
    location: NotRequired[str]
    r"""Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'"""
    message: NotRequired[str]
    r"""Error message text"""
    value: NotRequired[Any]
    r"""The value at the given location"""


class ErrorDetail(BaseModel):
    location: Optional[str] = None
    r"""Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'"""

    message: Optional[str] = None
    r"""Error message text"""

    value: Optional[Any] = None
    r"""The value at the given location"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["location", "message", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
