"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errormodel import ErrorModel, ErrorModelTypedDict
from .estimatemodelapplicationinputbody import (
    EstimateModelApplicationInputBody,
    EstimateModelApplicationInputBodyTypedDict,
)
from .estimatemodelresponse import EstimateModelResponse, EstimateModelResponseTypedDict
from flypix.types import BaseModel
from flypix.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class EstimateModelApplicationOnFileRequestTypedDict(TypedDict):
    model_id: str
    body: EstimateModelApplicationInputBodyTypedDict


class EstimateModelApplicationOnFileRequest(BaseModel):
    model_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        EstimateModelApplicationInputBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


EstimateModelApplicationOnFileResponseTypedDict = TypeAliasType(
    "EstimateModelApplicationOnFileResponseTypedDict",
    Union[EstimateModelResponseTypedDict, ErrorModelTypedDict],
)


EstimateModelApplicationOnFileResponse = TypeAliasType(
    "EstimateModelApplicationOnFileResponse", Union[EstimateModelResponse, ErrorModel]
)
