"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel
from flypix.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class FilesGetDownloadLinkRequestTypedDict(TypedDict):
    file_id: str


class FilesGetDownloadLinkRequest(BaseModel):
    file_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
