"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel
from flypix.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict
from uuid import UUID


class FoldersListForFolderRequestTypedDict(TypedDict):
    folder_id: UUID


class FoldersListForFolderRequest(BaseModel):
    folder_id: Annotated[
        UUID, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
