"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import TypedDict


class FolderResponseTypedDict(TypedDict):
    folder_id: str
    r"""A string in UUID format"""
    name: str
    parent_id: Nullable[str]


class FolderResponse(BaseModel):
    folder_id: str
    r"""A string in UUID format"""

    name: str

    parent_id: Nullable[str]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
