"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .sendmessagerequest import SendMessageRequest, SendMessageRequestTypedDict
from flypix.types import BaseModel
from flypix.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict
from uuid import UUID


class GeosenseSendMessageRequestTypedDict(TypedDict):
    session_id: UUID
    body: SendMessageRequestTypedDict


class GeosenseSendMessageRequest(BaseModel):
    session_id: Annotated[
        UUID, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        SendMessageRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
