"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errormodel import ErrorModel, ErrorModelTypedDict
from .tenantresponse import TenantResponse, TenantResponseTypedDict
from typing import List, Union
from typing_extensions import TypeAliasType


GetTenantsForUserResponseTypedDict = TypeAliasType(
    "GetTenantsForUserResponseTypedDict",
    Union[ErrorModelTypedDict, List[TenantResponseTypedDict]],
)


GetTenantsForUserResponse = TypeAliasType(
    "GetTenantsForUserResponse", Union[ErrorModel, List[TenantResponse]]
)
