"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errormodel import ErrorModel, ErrorModelTypedDict
from .inferenceresponse import InferenceResponse, InferenceResponseTypedDict
from typing import List, Union
from typing_extensions import TypeAliasType


GetInferencesByIdsResponseTypedDict = TypeAliasType(
    "GetInferencesByIdsResponseTypedDict",
    Union[ErrorModelTypedDict, List[InferenceResponseTypedDict]],
)


GetInferencesByIdsResponse = TypeAliasType(
    "GetInferencesByIdsResponse", Union[ErrorModel, List[InferenceResponse]]
)
