"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errormodel import ErrorModel, ErrorModelTypedDict
from .vectorfeatures import VectorFeatures, VectorFeaturesTypedDict
from flypix.types import BaseModel
from flypix.utils import FieldMetadata, PathParamMetadata
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class GetVectorFeaturesRequestTypedDict(TypedDict):
    vector_id: str


class GetVectorFeaturesRequest(BaseModel):
    vector_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


GetVectorFeaturesResponseTypedDict = TypeAliasType(
    "GetVectorFeaturesResponseTypedDict",
    Union[VectorFeaturesTypedDict, ErrorModelTypedDict],
)


GetVectorFeaturesResponse = TypeAliasType(
    "GetVectorFeaturesResponse", Union[VectorFeatures, ErrorModel]
)
