"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errormodel import ErrorModel, ErrorModelTypedDict
from .projectresponse import ProjectResponse, ProjectResponseTypedDict
from flypix.types import BaseModel
from flypix.utils import FieldMetadata, PathParamMetadata
from typing import List, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class GetProjectsForTenantRequestTypedDict(TypedDict):
    tenant_id: str


class GetProjectsForTenantRequest(BaseModel):
    tenant_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


GetProjectsForTenantResponseTypedDict = TypeAliasType(
    "GetProjectsForTenantResponseTypedDict",
    Union[ErrorModelTypedDict, List[ProjectResponseTypedDict]],
)


GetProjectsForTenantResponse = TypeAliasType(
    "GetProjectsForTenantResponse", Union[ErrorModel, List[ProjectResponse]]
)
