"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errormodel import ErrorModel, ErrorModelTypedDict
from .regionresponse import RegionResponse, RegionResponseTypedDict
from flypix.types import BaseModel
from flypix.utils import FieldMetadata, PathParamMetadata
from typing import List, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class GetRegionsForRasterRequestTypedDict(TypedDict):
    raster_id: str


class GetRegionsForRasterRequest(BaseModel):
    raster_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


GetRegionsForRasterResponseTypedDict = TypeAliasType(
    "GetRegionsForRasterResponseTypedDict",
    Union[ErrorModelTypedDict, List[RegionResponseTypedDict]],
)


GetRegionsForRasterResponse = TypeAliasType(
    "GetRegionsForRasterResponse", Union[ErrorModel, List[RegionResponse]]
)
