"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errormodel import ErrorModel, ErrorModelTypedDict
from .folderresponse import FolderResponse, FolderResponseTypedDict
from typing import List, Union
from typing_extensions import TypeAliasType


GetFoldersByIdsResponseTypedDict = TypeAliasType(
    "GetFoldersByIdsResponseTypedDict",
    Union[ErrorModelTypedDict, List[FolderResponseTypedDict]],
)


GetFoldersByIdsResponse = TypeAliasType(
    "GetFoldersByIdsResponse", Union[ErrorModel, List[FolderResponse]]
)
