"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .classresponse import ClassResponse, ClassResponseTypedDict
from .errormodel import ErrorModel, ErrorModelTypedDict
from flypix.types import BaseModel
from flypix.utils import FieldMetadata, PathParamMetadata
from typing import List, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class GetClassesForProjectRequestTypedDict(TypedDict):
    project_id: str


class GetClassesForProjectRequest(BaseModel):
    project_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


GetClassesForProjectResponseTypedDict = TypeAliasType(
    "GetClassesForProjectResponseTypedDict",
    Union[ErrorModelTypedDict, List[ClassResponseTypedDict]],
)


GetClassesForProjectResponse = TypeAliasType(
    "GetClassesForProjectResponse", Union[ErrorModel, List[ClassResponse]]
)
