"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errormodel import ErrorModel, ErrorModelTypedDict
from .filelinkresponse import FileLinkResponse, FileLinkResponseTypedDict
from flypix.types import BaseModel
from flypix.utils import FieldMetadata, PathParamMetadata
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class GetFileDownloadLinkRequestTypedDict(TypedDict):
    file_id: str


class GetFileDownloadLinkRequest(BaseModel):
    file_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


GetFileDownloadLinkResponseTypedDict = TypeAliasType(
    "GetFileDownloadLinkResponseTypedDict",
    Union[FileLinkResponseTypedDict, ErrorModelTypedDict],
)


GetFileDownloadLinkResponse = TypeAliasType(
    "GetFileDownloadLinkResponse", Union[FileLinkResponse, ErrorModel]
)
