"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errormodel import ErrorModel, ErrorModelTypedDict
from .rasterresponse import RasterResponse, RasterResponseTypedDict
from flypix.types import BaseModel
from flypix.utils import FieldMetadata, PathParamMetadata
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class GetRasterRequestTypedDict(TypedDict):
    raster_id: str


class GetRasterRequest(BaseModel):
    raster_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


GetRasterResponseTypedDict = TypeAliasType(
    "GetRasterResponseTypedDict", Union[ErrorModelTypedDict, RasterResponseTypedDict]
)


GetRasterResponse = TypeAliasType(
    "GetRasterResponse", Union[ErrorModel, RasterResponse]
)
