"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errormodel import ErrorModel, ErrorModelTypedDict
from .regionresponse import RegionResponse, RegionResponseTypedDict
from typing import List, Union
from typing_extensions import TypeAliasType


GetRegionsByIdsResponseTypedDict = TypeAliasType(
    "GetRegionsByIdsResponseTypedDict",
    Union[ErrorModelTypedDict, List[RegionResponseTypedDict]],
)


GetRegionsByIdsResponse = TypeAliasType(
    "GetRegionsByIdsResponse", Union[ErrorModel, List[RegionResponse]]
)
