"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .artifactresponse import ArtifactResponse, ArtifactResponseTypedDict
from .errormodel import ErrorModel, ErrorModelTypedDict
from flypix.types import BaseModel
from flypix.utils import FieldMetadata, PathParamMetadata
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class GetSessionArtifactRequestTypedDict(TypedDict):
    session_id: str
    artifact_id: str


class GetSessionArtifactRequest(BaseModel):
    session_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    artifact_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


GetSessionArtifactResponseTypedDict = TypeAliasType(
    "GetSessionArtifactResponseTypedDict",
    Union[ErrorModelTypedDict, ArtifactResponseTypedDict],
)


GetSessionArtifactResponse = TypeAliasType(
    "GetSessionArtifactResponse", Union[ErrorModel, ArtifactResponse]
)
