"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .balance import Balance, BalanceTypedDict
from .errormodel import ErrorModel, ErrorModelTypedDict
from flypix.types import BaseModel
from flypix.utils import FieldMetadata, PathParamMetadata
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class GetTenantBalanceRequestTypedDict(TypedDict):
    tenant_id: str


class GetTenantBalanceRequest(BaseModel):
    tenant_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


GetTenantBalanceResponseTypedDict = TypeAliasType(
    "GetTenantBalanceResponseTypedDict", Union[BalanceTypedDict, ErrorModelTypedDict]
)


GetTenantBalanceResponse = TypeAliasType(
    "GetTenantBalanceResponse", Union[Balance, ErrorModel]
)
