"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errormodel import ErrorModel, ErrorModelTypedDict
from .healthoutputbody import HealthOutputBody, HealthOutputBodyTypedDict
from typing import Union
from typing_extensions import TypeAliasType


HealthResponseTypedDict = TypeAliasType(
    "HealthResponseTypedDict", Union[HealthOutputBodyTypedDict, ErrorModelTypedDict]
)


HealthResponse = TypeAliasType("HealthResponse", Union[HealthOutputBody, ErrorModel])
