"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel
from typing_extensions import TypedDict


class LoginWithPasswordInputBodyTypedDict(TypedDict):
    password: str
    username: str


class LoginWithPasswordInputBody(BaseModel):
    password: str

    username: str
