"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


MessageContextInputType = Literal["data",]


class MessageContextInputTypedDict(TypedDict):
    artifact_id: str
    type: MessageContextInputType


class MessageContextInput(BaseModel):
    artifact_id: str

    type: MessageContextInputType
