"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .applymodelrequest import ApplyModelRequest, ApplyModelRequestTypedDict
from flypix.types import BaseModel
from flypix.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ModelsEstimateApplicationRequestTypedDict(TypedDict):
    model_id: str
    body: ApplyModelRequestTypedDict


class ModelsEstimateApplicationRequest(BaseModel):
    model_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        ApplyModelRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
