"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel
from typing_extensions import TypedDict


class ProjectCreationRequestTypedDict(TypedDict):
    tenant_id: str
    r"""A string in UUID format"""
    name: str


class ProjectCreationRequest(BaseModel):
    tenant_id: str
    r"""A string in UUID format"""

    name: str
