"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .rastersource import RasterSource, RasterSourceTypedDict
from .rasterstatus import RasterStatus
from datetime import datetime
from flypix.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class RasterResponseTypedDict(TypedDict):
    raster_id: str
    r"""A string in UUID format"""
    tenant_id: str
    r"""A string in UUID format"""
    project_id: Nullable[str]
    file_id: str
    r"""A string in UUID format"""
    status: RasterStatus
    source: RasterSourceTypedDict
    created_at: datetime
    cog_file_id: NotRequired[Nullable[str]]


class RasterResponse(BaseModel):
    raster_id: str
    r"""A string in UUID format"""

    tenant_id: str
    r"""A string in UUID format"""

    project_id: Nullable[str]

    file_id: str
    r"""A string in UUID format"""

    status: RasterStatus

    source: RasterSource

    created_at: datetime

    cog_file_id: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cog_file_id"])
        nullable_fields = set(["project_id", "cog_file_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
