"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cograstersource import COGRasterSource, COGRasterSourceTypedDict
from .osmrastersource import OSMRasterSource, OSMRasterSourceTypedDict
from .uploadrastersource import UploadRasterSource, UploadRasterSourceTypedDict
from .wmtsrastersource import WMTSRasterSource, WMTSRasterSourceTypedDict
from datetime import datetime
from flypix.types import BaseModel, Nullable, UNSET_SENTINEL
from flypix.utils.unions import parse_open_union
from functools import partial
import pydantic
from pydantic import ConfigDict, model_serializer
from pydantic.functional_validators import BeforeValidator
from typing import Any, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


SourceTypedDict = TypeAliasType(
    "SourceTypedDict",
    Union[
        COGRasterSourceTypedDict,
        OSMRasterSourceTypedDict,
        WMTSRasterSourceTypedDict,
        UploadRasterSourceTypedDict,
    ],
)


class UnknownSource(BaseModel):
    r"""A Source variant the SDK doesn't recognize. Preserves the raw payload."""

    type: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_SOURCE_VARIANTS: dict[str, Any] = {
    "EXTERNAL_COG": COGRasterSource,
    "OSM": OSMRasterSource,
    "UPLOAD": UploadRasterSource,
    "WMTS": WMTSRasterSource,
}


Source = Annotated[
    Union[
        COGRasterSource,
        OSMRasterSource,
        UploadRasterSource,
        WMTSRasterSource,
        UnknownSource,
    ],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="type",
            variants=_SOURCE_VARIANTS,
            unknown_cls=UnknownSource,
            union_name="Source",
        )
    ),
]


class RasterResponseTypedDict(TypedDict):
    created_at: datetime
    folder_id: Nullable[str]
    name: str
    project_id: Nullable[str]
    raster_id: str
    source: SourceTypedDict
    status: str
    tenant_id: str
    dollar_schema: NotRequired[str]
    r"""A URL to the JSON Schema for this object."""


class RasterResponse(BaseModel):
    created_at: datetime

    folder_id: Nullable[str]

    name: str

    project_id: Nullable[str]

    raster_id: str

    source: Source

    status: str

    tenant_id: str

    dollar_schema: Annotated[Optional[str], pydantic.Field(alias="$schema")] = None
    r"""A URL to the JSON Schema for this object."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["$schema"])
        nullable_fields = set(["folder_id", "project_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    RasterResponse.model_rebuild()
except NameError:
    pass
