"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import UnrecognizedStr
from typing import Literal, Union


RegionTrainingBehavior = Union[
    Literal[
        "TRAINING",
        "VALIDATION",
        "TEST",
        "IGNORE",
    ],
    UnrecognizedStr,
]
