"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .regionmetadata import RegionMetadata, RegionMetadataTypedDict
from flypix.types import BaseModel
from typing_extensions import TypedDict


class RegionResponseTypedDict(TypedDict):
    inference_behavior: str
    metadata: RegionMetadataTypedDict
    polygon: str
    project_id: str
    raster_id: str
    region_id: str
    tenant_id: str
    training_behavior: str


class RegionResponse(BaseModel):
    inference_behavior: str

    metadata: RegionMetadata

    polygon: str

    project_id: str

    raster_id: str

    region_id: str

    tenant_id: str

    training_behavior: str
