"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel
from typing_extensions import TypedDict


class TenantResponseTypedDict(TypedDict):
    name: str
    tenant_id: str


class TenantResponse(BaseModel):
    name: str

    tenant_id: str
