"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .reason import Reason
from .transactiontype import TransactionType
from datetime import datetime
from flypix.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import TypedDict


class TransactionResponseTypedDict(TypedDict):
    transaction_id: str
    r"""A string in UUID format"""
    tenant_id: str
    r"""A string in UUID format"""
    project_id: Nullable[str]
    reference_id: Nullable[str]
    credits: float
    reason: Reason
    type: TransactionType
    created_at: datetime


class TransactionResponse(BaseModel):
    transaction_id: str
    r"""A string in UUID format"""

    tenant_id: str
    r"""A string in UUID format"""

    project_id: Nullable[str]

    reference_id: Nullable[str]

    credits: float

    reason: Reason

    type: TransactionType

    created_at: datetime

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
