"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from flypix.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import TypedDict


class TransactionTypedDict(TypedDict):
    created_at: datetime
    credits: float
    project_id: Nullable[str]
    reason: str
    reference_id: Nullable[str]
    tenant_id: str
    transaction_id: str
    type: str


class Transaction(BaseModel):
    created_at: datetime

    credits: float

    project_id: Nullable[str]

    reason: str

    reference_id: Nullable[str]

    tenant_id: str

    transaction_id: str

    type: str

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
