"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errormodel import ErrorModel, ErrorModelTypedDict
from .uploadannotationsoutputbody import (
    UploadAnnotationsOutputBody,
    UploadAnnotationsOutputBodyTypedDict,
)
from flypix.types import BaseModel, UNSET_SENTINEL
from flypix.utils import (
    FieldMetadata,
    MultipartFormMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import io
import pydantic
from pydantic import model_serializer
from typing import IO, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class UploadGeopkgFileTypedDict(TypedDict):
    file_name: str
    content: Union[bytes, IO[bytes], io.IOBase]
    content_type: NotRequired[str]


class UploadGeopkgFile(BaseModel):
    file_name: Annotated[
        str, pydantic.Field(alias="fileName"), FieldMetadata(multipart=True)
    ]

    content: Annotated[
        Union[bytes, IO[bytes], io.IOBase],
        pydantic.Field(alias=""),
        FieldMetadata(multipart=MultipartFormMetadata(content=True)),
    ]

    content_type: Annotated[
        Optional[str],
        pydantic.Field(alias="Content-Type"),
        FieldMetadata(multipart=True),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["contentType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UploadGeopkgRequestBodyTypedDict(TypedDict):
    file: UploadGeopkgFileTypedDict


class UploadGeopkgRequestBody(BaseModel):
    file: Annotated[
        UploadGeopkgFile, FieldMetadata(multipart=MultipartFormMetadata(file=True))
    ]


class UploadGeopkgRequestTypedDict(TypedDict):
    vector_id: str
    body: NotRequired[UploadGeopkgRequestBodyTypedDict]


class UploadGeopkgRequest(BaseModel):
    vector_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        Optional[UploadGeopkgRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="multipart/form-data")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["body"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


UploadGeopkgResponseTypedDict = TypeAliasType(
    "UploadGeopkgResponseTypedDict",
    Union[UploadAnnotationsOutputBodyTypedDict, ErrorModelTypedDict],
)


UploadGeopkgResponse = TypeAliasType(
    "UploadGeopkgResponse", Union[UploadAnnotationsOutputBody, ErrorModel]
)
