"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel
from typing import List, Union
from typing_extensions import TypeAliasType, TypedDict


ErroredTypedDict = TypeAliasType("ErroredTypedDict", Union[int, str])


Errored = TypeAliasType("Errored", Union[int, str])


class UploadAnnotationsResponseTypedDict(TypedDict):
    annotation_ids: List[int]
    errored: List[List[ErroredTypedDict]]


class UploadAnnotationsResponse(BaseModel):
    annotation_ids: List[int]

    errored: List[List[Errored]]
