"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict
from uuid import UUID


class UsageResponseTypedDict(TypedDict):
    tenant_id: UUID
    r"""A string in UUID format"""
    bytes_: int
    storage_quota: int


class UsageResponse(BaseModel):
    tenant_id: UUID
    r"""A string in UUID format"""

    bytes_: Annotated[int, pydantic.Field(alias="bytes")]

    storage_quota: int


try:
    UsageResponse.model_rebuild()
except NameError:
    pass
