"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class VectorFeaturesDataTypedDict(TypedDict):
    areas: Nullable[List[float]]
    class_ids: Nullable[List[int]]
    confidences: Nullable[List[float]]
    ids: Nullable[List[int]]
    polygons: Nullable[List[str]]


class VectorFeaturesData(BaseModel):
    areas: Nullable[List[float]]

    class_ids: Nullable[List[int]]

    confidences: Nullable[List[float]]

    ids: Nullable[List[int]]

    polygons: Nullable[List[str]]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
