"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .vectorfeaturesdata import VectorFeaturesData, VectorFeaturesDataTypedDict
from flypix.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class VectorFeaturesTypedDict(TypedDict):
    classes: Dict[str, str]
    data: VectorFeaturesDataTypedDict
    dollar_schema: NotRequired[str]
    r"""A URL to the JSON Schema for this object."""


class VectorFeatures(BaseModel):
    classes: Dict[str, str]

    data: VectorFeaturesData

    dollar_schema: Annotated[Optional[str], pydantic.Field(alias="$schema")] = None
    r"""A URL to the JSON Schema for this object."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["$schema"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    VectorFeatures.model_rebuild()
except NameError:
    pass
