"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class VectorFeaturesDictTypedDict(TypedDict):
    ids: List[int]
    areas: List[float]
    polygons: List[str]
    confidences: List[float]
    class_ids: List[int]


class VectorFeaturesDict(BaseModel):
    ids: List[int]

    areas: List[float]

    polygons: List[str]

    confidences: List[float]

    class_ids: List[int]
