"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flypix.types import BaseModel, UNSET_SENTINEL
from flypix.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, TypedDict


class WMTSSourceTypedDict(TypedDict):
    layer: str
    url: str
    type: Literal["WMTS"]


class WMTSSource(BaseModel):
    layer: str

    url: str

    type: Annotated[
        Annotated[Optional[Literal["WMTS"]], AfterValidator(validate_const("WMTS"))],
        pydantic.Field(alias="type"),
    ] = "WMTS"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    WMTSSource.model_rebuild()
except NameError:
    pass
