"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from flypix.errors import FlyPixError
from flypix.types import BaseModel
import httpx
from typing import Optional


class AuthLoginWithPasswordInternalServerErrorErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class AuthLoginWithPasswordInternalServerErrorErrorResponseSchema(FlyPixError):
    r"""Internal server error"""

    data: AuthLoginWithPasswordInternalServerErrorErrorResponseSchemaData = field(
        hash=False
    )

    def __init__(
        self,
        data: AuthLoginWithPasswordInternalServerErrorErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class AuthLoginWithPasswordNotFoundErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class AuthLoginWithPasswordNotFoundErrorResponseSchema(FlyPixError):
    r"""Bad Request"""

    data: AuthLoginWithPasswordNotFoundErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: AuthLoginWithPasswordNotFoundErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class AuthLoginWithPasswordForbiddenErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class AuthLoginWithPasswordForbiddenErrorResponseSchema(FlyPixError):
    r"""Not Found"""

    data: AuthLoginWithPasswordForbiddenErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: AuthLoginWithPasswordForbiddenErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class AuthLoginWithPasswordBadRequestErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class AuthLoginWithPasswordBadRequestErrorResponseSchema(FlyPixError):
    r"""Forbidden"""

    data: AuthLoginWithPasswordBadRequestErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: AuthLoginWithPasswordBadRequestErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
