"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from flypix.errors import FlyPixError
from flypix.types import BaseModel
import httpx
from typing import Optional


class FilesGetByIdsInternalServerErrorErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class FilesGetByIdsInternalServerErrorErrorResponseSchema(FlyPixError):
    r"""Internal server error"""

    data: FilesGetByIdsInternalServerErrorErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: FilesGetByIdsInternalServerErrorErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class FilesGetByIdsNotFoundErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class FilesGetByIdsNotFoundErrorResponseSchema(FlyPixError):
    r"""Bad Request"""

    data: FilesGetByIdsNotFoundErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: FilesGetByIdsNotFoundErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class FilesGetByIdsForbiddenErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class FilesGetByIdsForbiddenErrorResponseSchema(FlyPixError):
    r"""Not Found"""

    data: FilesGetByIdsForbiddenErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: FilesGetByIdsForbiddenErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class FilesGetByIdsBadRequestErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class FilesGetByIdsBadRequestErrorResponseSchema(FlyPixError):
    r"""Forbidden"""

    data: FilesGetByIdsBadRequestErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: FilesGetByIdsBadRequestErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
