"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from flypix.errors import FlyPixError
from flypix.types import BaseModel
import httpx
from typing import Optional


class FoldersListForProjectInternalServerErrorErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class FoldersListForProjectInternalServerErrorErrorResponseSchema(FlyPixError):
    r"""Internal server error"""

    data: FoldersListForProjectInternalServerErrorErrorResponseSchemaData = field(
        hash=False
    )

    def __init__(
        self,
        data: FoldersListForProjectInternalServerErrorErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class FoldersListForProjectNotFoundErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class FoldersListForProjectNotFoundErrorResponseSchema(FlyPixError):
    r"""Bad Request"""

    data: FoldersListForProjectNotFoundErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: FoldersListForProjectNotFoundErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class FoldersListForProjectForbiddenErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class FoldersListForProjectForbiddenErrorResponseSchema(FlyPixError):
    r"""Not Found"""

    data: FoldersListForProjectForbiddenErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: FoldersListForProjectForbiddenErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class FoldersListForProjectBadRequestErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class FoldersListForProjectBadRequestErrorResponseSchema(FlyPixError):
    r"""Forbidden"""

    data: FoldersListForProjectBadRequestErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: FoldersListForProjectBadRequestErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
