"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from flypix.errors import FlyPixError
from flypix.types import BaseModel
import httpx
from typing import Optional


class GeosenseGetArtifactInternalServerErrorErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class GeosenseGetArtifactInternalServerErrorErrorResponseSchema(FlyPixError):
    r"""Internal server error"""

    data: GeosenseGetArtifactInternalServerErrorErrorResponseSchemaData = field(
        hash=False
    )

    def __init__(
        self,
        data: GeosenseGetArtifactInternalServerErrorErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class GeosenseGetArtifactNotFoundErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class GeosenseGetArtifactNotFoundErrorResponseSchema(FlyPixError):
    r"""Bad Request"""

    data: GeosenseGetArtifactNotFoundErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: GeosenseGetArtifactNotFoundErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class GeosenseGetArtifactForbiddenErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class GeosenseGetArtifactForbiddenErrorResponseSchema(FlyPixError):
    r"""Not Found"""

    data: GeosenseGetArtifactForbiddenErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: GeosenseGetArtifactForbiddenErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class GeosenseGetArtifactBadRequestErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class GeosenseGetArtifactBadRequestErrorResponseSchema(FlyPixError):
    r"""Forbidden"""

    data: GeosenseGetArtifactBadRequestErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: GeosenseGetArtifactBadRequestErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
