"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from flypix.errors import FlyPixError
from flypix.types import BaseModel
import httpx
from typing import Optional


class GeosenseCreateArtifactInternalServerErrorErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class GeosenseCreateArtifactInternalServerErrorErrorResponseSchema(FlyPixError):
    r"""Internal server error"""

    data: GeosenseCreateArtifactInternalServerErrorErrorResponseSchemaData = field(
        hash=False
    )

    def __init__(
        self,
        data: GeosenseCreateArtifactInternalServerErrorErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class GeosenseCreateArtifactNotFoundErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class GeosenseCreateArtifactNotFoundErrorResponseSchema(FlyPixError):
    r"""Bad Request"""

    data: GeosenseCreateArtifactNotFoundErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: GeosenseCreateArtifactNotFoundErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class GeosenseCreateArtifactForbiddenErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class GeosenseCreateArtifactForbiddenErrorResponseSchema(FlyPixError):
    r"""Not Found"""

    data: GeosenseCreateArtifactForbiddenErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: GeosenseCreateArtifactForbiddenErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class GeosenseCreateArtifactBadRequestErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class GeosenseCreateArtifactBadRequestErrorResponseSchema(FlyPixError):
    r"""Forbidden"""

    data: GeosenseCreateArtifactBadRequestErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: GeosenseCreateArtifactBadRequestErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
