"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from flypix.errors import FlyPixError
from flypix.types import BaseModel
import httpx
from typing import Optional


class GetTenantTransactionsPaymentsBalanceTenantIDTransactionsGetInternalServerErrorErrorResponseSchemaData(
    BaseModel
):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class GetTenantTransactionsPaymentsBalanceTenantIDTransactionsGetInternalServerErrorErrorResponseSchema(
    FlyPixError
):
    r"""Internal server error"""

    data: GetTenantTransactionsPaymentsBalanceTenantIDTransactionsGetInternalServerErrorErrorResponseSchemaData = field(
        hash=False
    )

    def __init__(
        self,
        data: GetTenantTransactionsPaymentsBalanceTenantIDTransactionsGetInternalServerErrorErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class GetTenantTransactionsPaymentsBalanceTenantIDTransactionsGetNotFoundErrorResponseSchemaData(
    BaseModel
):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class GetTenantTransactionsPaymentsBalanceTenantIDTransactionsGetNotFoundErrorResponseSchema(
    FlyPixError
):
    r"""Bad Request"""

    data: GetTenantTransactionsPaymentsBalanceTenantIDTransactionsGetNotFoundErrorResponseSchemaData = field(
        hash=False
    )

    def __init__(
        self,
        data: GetTenantTransactionsPaymentsBalanceTenantIDTransactionsGetNotFoundErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class GetTenantTransactionsPaymentsBalanceTenantIDTransactionsGetForbiddenErrorResponseSchemaData(
    BaseModel
):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class GetTenantTransactionsPaymentsBalanceTenantIDTransactionsGetForbiddenErrorResponseSchema(
    FlyPixError
):
    r"""Not Found"""

    data: GetTenantTransactionsPaymentsBalanceTenantIDTransactionsGetForbiddenErrorResponseSchemaData = field(
        hash=False
    )

    def __init__(
        self,
        data: GetTenantTransactionsPaymentsBalanceTenantIDTransactionsGetForbiddenErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class GetTenantTransactionsPaymentsBalanceTenantIDTransactionsGetBadRequestErrorResponseSchemaData(
    BaseModel
):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class GetTenantTransactionsPaymentsBalanceTenantIDTransactionsGetBadRequestErrorResponseSchema(
    FlyPixError
):
    r"""Forbidden"""

    data: GetTenantTransactionsPaymentsBalanceTenantIDTransactionsGetBadRequestErrorResponseSchemaData = field(
        hash=False
    )

    def __init__(
        self,
        data: GetTenantTransactionsPaymentsBalanceTenantIDTransactionsGetBadRequestErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
