"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from flypix.errors import FlyPixError
from flypix.types import BaseModel
import httpx
from typing import Optional


class ModelsGetInferenceStatusInternalServerErrorErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class ModelsGetInferenceStatusInternalServerErrorErrorResponseSchema(FlyPixError):
    r"""Internal server error"""

    data: ModelsGetInferenceStatusInternalServerErrorErrorResponseSchemaData = field(
        hash=False
    )

    def __init__(
        self,
        data: ModelsGetInferenceStatusInternalServerErrorErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class ModelsGetInferenceStatusNotFoundErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class ModelsGetInferenceStatusNotFoundErrorResponseSchema(FlyPixError):
    r"""Bad Request"""

    data: ModelsGetInferenceStatusNotFoundErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: ModelsGetInferenceStatusNotFoundErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class ModelsGetInferenceStatusForbiddenErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class ModelsGetInferenceStatusForbiddenErrorResponseSchema(FlyPixError):
    r"""Not Found"""

    data: ModelsGetInferenceStatusForbiddenErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: ModelsGetInferenceStatusForbiddenErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class ModelsGetInferenceStatusBadRequestErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class ModelsGetInferenceStatusBadRequestErrorResponseSchema(FlyPixError):
    r"""Forbidden"""

    data: ModelsGetInferenceStatusBadRequestErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: ModelsGetInferenceStatusBadRequestErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
