"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from flypix.errors import FlyPixError
from flypix.types import BaseModel
import httpx
from typing import Optional


class ModelsListOfficialInternalServerErrorErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class ModelsListOfficialInternalServerErrorErrorResponseSchema(FlyPixError):
    r"""Internal server error"""

    data: ModelsListOfficialInternalServerErrorErrorResponseSchemaData = field(
        hash=False
    )

    def __init__(
        self,
        data: ModelsListOfficialInternalServerErrorErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class ModelsListOfficialNotFoundErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class ModelsListOfficialNotFoundErrorResponseSchema(FlyPixError):
    r"""Bad Request"""

    data: ModelsListOfficialNotFoundErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: ModelsListOfficialNotFoundErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class ModelsListOfficialForbiddenErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class ModelsListOfficialForbiddenErrorResponseSchema(FlyPixError):
    r"""Not Found"""

    data: ModelsListOfficialForbiddenErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: ModelsListOfficialForbiddenErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class ModelsListOfficialBadRequestErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class ModelsListOfficialBadRequestErrorResponseSchema(FlyPixError):
    r"""Forbidden"""

    data: ModelsListOfficialBadRequestErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: ModelsListOfficialBadRequestErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
