"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from flypix.errors import FlyPixError
from flypix.types import BaseModel
import httpx
from typing import Optional


class ProjectsCreateInternalServerErrorErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class ProjectsCreateInternalServerErrorErrorResponseSchema(FlyPixError):
    r"""Internal server error"""

    data: ProjectsCreateInternalServerErrorErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: ProjectsCreateInternalServerErrorErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class ProjectsCreateNotFoundErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class ProjectsCreateNotFoundErrorResponseSchema(FlyPixError):
    r"""Bad Request"""

    data: ProjectsCreateNotFoundErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: ProjectsCreateNotFoundErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class ProjectsCreateForbiddenErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class ProjectsCreateForbiddenErrorResponseSchema(FlyPixError):
    r"""Not Found"""

    data: ProjectsCreateForbiddenErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: ProjectsCreateForbiddenErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class ProjectsCreateBadRequestErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class ProjectsCreateBadRequestErrorResponseSchema(FlyPixError):
    r"""Forbidden"""

    data: ProjectsCreateBadRequestErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: ProjectsCreateBadRequestErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
