"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from flypix.errors import FlyPixError
from flypix.types import BaseModel
import httpx
from typing import Optional


class RegionsListForFileInternalServerErrorErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class RegionsListForFileInternalServerErrorErrorResponseSchema(FlyPixError):
    r"""Internal server error"""

    data: RegionsListForFileInternalServerErrorErrorResponseSchemaData = field(
        hash=False
    )

    def __init__(
        self,
        data: RegionsListForFileInternalServerErrorErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class RegionsListForFileNotFoundErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class RegionsListForFileNotFoundErrorResponseSchema(FlyPixError):
    r"""Bad Request"""

    data: RegionsListForFileNotFoundErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: RegionsListForFileNotFoundErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class RegionsListForFileForbiddenErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class RegionsListForFileForbiddenErrorResponseSchema(FlyPixError):
    r"""Not Found"""

    data: RegionsListForFileForbiddenErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: RegionsListForFileForbiddenErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class RegionsListForFileBadRequestErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class RegionsListForFileBadRequestErrorResponseSchema(FlyPixError):
    r"""Forbidden"""

    data: RegionsListForFileBadRequestErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: RegionsListForFileBadRequestErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
