"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from flypix.errors import FlyPixError
from flypix.types import BaseModel
import httpx
from typing import Optional


class RegionsCreateInternalServerErrorErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class RegionsCreateInternalServerErrorErrorResponseSchema(FlyPixError):
    r"""Internal server error"""

    data: RegionsCreateInternalServerErrorErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: RegionsCreateInternalServerErrorErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class RegionsCreateNotFoundErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class RegionsCreateNotFoundErrorResponseSchema(FlyPixError):
    r"""Bad Request"""

    data: RegionsCreateNotFoundErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: RegionsCreateNotFoundErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class RegionsCreateForbiddenErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class RegionsCreateForbiddenErrorResponseSchema(FlyPixError):
    r"""Not Found"""

    data: RegionsCreateForbiddenErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: RegionsCreateForbiddenErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class RegionsCreateBadRequestErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class RegionsCreateBadRequestErrorResponseSchema(FlyPixError):
    r"""Forbidden"""

    data: RegionsCreateBadRequestErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: RegionsCreateBadRequestErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
