"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from flypix.errors import FlyPixError
from flypix.types import BaseModel
import httpx
from typing import Optional


class VectorsDeleteInternalServerErrorErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class VectorsDeleteInternalServerErrorErrorResponseSchema(FlyPixError):
    r"""Internal server error"""

    data: VectorsDeleteInternalServerErrorErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: VectorsDeleteInternalServerErrorErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class VectorsDeleteNotFoundErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class VectorsDeleteNotFoundErrorResponseSchema(FlyPixError):
    r"""Bad Request"""

    data: VectorsDeleteNotFoundErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: VectorsDeleteNotFoundErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class VectorsDeleteForbiddenErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class VectorsDeleteForbiddenErrorResponseSchema(FlyPixError):
    r"""Not Found"""

    data: VectorsDeleteForbiddenErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: VectorsDeleteForbiddenErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class VectorsDeleteBadRequestErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class VectorsDeleteBadRequestErrorResponseSchema(FlyPixError):
    r"""Forbidden"""

    data: VectorsDeleteBadRequestErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: VectorsDeleteBadRequestErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
