"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from flypix.errors import FlyPixError
from flypix.types import BaseModel
import httpx
from typing import Optional


class VectorsListClassesForProjectInternalServerErrorErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class VectorsListClassesForProjectInternalServerErrorErrorResponseSchema(FlyPixError):
    r"""Internal server error"""

    data: VectorsListClassesForProjectInternalServerErrorErrorResponseSchemaData = (
        field(hash=False)
    )

    def __init__(
        self,
        data: VectorsListClassesForProjectInternalServerErrorErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class VectorsListClassesForProjectNotFoundErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class VectorsListClassesForProjectNotFoundErrorResponseSchema(FlyPixError):
    r"""Bad Request"""

    data: VectorsListClassesForProjectNotFoundErrorResponseSchemaData = field(
        hash=False
    )

    def __init__(
        self,
        data: VectorsListClassesForProjectNotFoundErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class VectorsListClassesForProjectForbiddenErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class VectorsListClassesForProjectForbiddenErrorResponseSchema(FlyPixError):
    r"""Not Found"""

    data: VectorsListClassesForProjectForbiddenErrorResponseSchemaData = field(
        hash=False
    )

    def __init__(
        self,
        data: VectorsListClassesForProjectForbiddenErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class VectorsListClassesForProjectBadRequestErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class VectorsListClassesForProjectBadRequestErrorResponseSchema(FlyPixError):
    r"""Forbidden"""

    data: VectorsListClassesForProjectBadRequestErrorResponseSchemaData = field(
        hash=False
    )

    def __init__(
        self,
        data: VectorsListClassesForProjectBadRequestErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
