"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from flypix.errors import FlyPixError
from flypix.types import BaseModel
import httpx
from typing import Optional


class VectorsUploadShapefileInternalServerErrorErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class VectorsUploadShapefileInternalServerErrorErrorResponseSchema(FlyPixError):
    r"""Internal server error"""

    data: VectorsUploadShapefileInternalServerErrorErrorResponseSchemaData = field(
        hash=False
    )

    def __init__(
        self,
        data: VectorsUploadShapefileInternalServerErrorErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class VectorsUploadShapefileNotFoundErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class VectorsUploadShapefileNotFoundErrorResponseSchema(FlyPixError):
    r"""Bad Request"""

    data: VectorsUploadShapefileNotFoundErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: VectorsUploadShapefileNotFoundErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class VectorsUploadShapefileForbiddenErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class VectorsUploadShapefileForbiddenErrorResponseSchema(FlyPixError):
    r"""Not Found"""

    data: VectorsUploadShapefileForbiddenErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: VectorsUploadShapefileForbiddenErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class VectorsUploadShapefileBadRequestErrorResponseSchemaData(BaseModel):
    error: str
    message: str


@dataclass(unsafe_hash=True)
class VectorsUploadShapefileBadRequestErrorResponseSchema(FlyPixError):
    r"""Forbidden"""

    data: VectorsUploadShapefileBadRequestErrorResponseSchemaData = field(hash=False)

    def __init__(
        self,
        data: VectorsUploadShapefileBadRequestErrorResponseSchemaData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
